title: Akaki Razmadze
email: contact@razmadze.ge
description: >-
  Graphic & Type Designer from Georgia
baseurl: ""
url: "https://razmadze.ge"
twitter_username: razmadzekoko
github_username: mijra

markdown: kramdown
# theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-assets
  
assets:
  sources:
    - assets/fonts

# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
